name: Unity CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build Unity Project
    runs-on: windows-latest  # Use Windows for compatibility with your setup

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Unity
      - name: Set up Unity
        uses: game-ci/unity-actions/setup@v2
        with:
          unityVersion: 2023.1.0f1  # Replace with your Unity version
          modules: Windows

      # Step 3: Activate Unity license using the .ulf content from GitHub Secrets
      - name: Activate Unity license
        uses: game-ci/unity-actions/activate@v2
        with:
          ulfContent: ${{ secrets.UNITY_LICENSE }}  # Use the secret where you've stored the .ulf content

      # Step 4: Build the project
      - name: Build project
        uses: game-ci/unity-actions/builder@v2
        with:
          targetPlatform: StandaloneWindows64  # Adjust for your platform
          buildName: MyGame
          buildPath: build/

      # Step 5: Upload Build Artifacts
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: GameBuild
          path: build/
